version: '3'

tasks:
  install:
    cmds:
      - go install cmd/main.go
      - cmd: echo 'Con install se mueve el ejecutable al $GOPATH/bin'
    silent: true

  run:
    cmds:
      - go run cmd/main.go
    silent: true

  dependencias:
    cmds:
      - go mod tidy
      - cmd: echo 'Se han incluido todas las dependencias necesarias en go.mod'

  test:
    cmds:
      - go test -v ./cmd/...